"""
Модуль конфигурации бота.

Содержит:
- settings.py: все константы, токены, настройки
"""

from .settings import (
    # Токены
    BOT_TOKEN,
    ANTHROPIC_API_KEY,
    CLAUDE_MODEL_OPUS,
    CLAUDE_MODEL_SONNET,
    CLAUDE_MODEL_HAIKU,
    DATABASE_URL,
    BOT_DATA_URL,
    PERSONA_URL,
    SUBSCRIPTION_URL,
    INDICATORS_URL,
    LEARNING_URL,
    REWARDS_URL,
    CONSENT_URL,
    FSM_URL,
    JOURNAL_URL,
    HEALTH_URL,
    KNOWLEDGE_MCP_URL,
    DIGITAL_TWIN_MCP_URL,
    GATEWAY_MCP_URL,
    validate_env,

    # Linear OAuth (тестовая интеграция)
    LINEAR_CLIENT_ID,
    LINEAR_CLIENT_SECRET,
    LINEAR_REDIRECT_URI,
    OAUTH_SERVER_PORT,

    # GitHub OAuth
    GITHUB_CLIENT_ID,
    GITHUB_CLIENT_SECRET,
    GITHUB_REDIRECT_URI,

    # Google Calendar OAuth (WP-128)
    GOOGLE_CALENDAR_CLIENT_ID,
    GOOGLE_CALENDAR_CLIENT_SECRET,
    GOOGLE_CALENDAR_REDIRECT_URI,

    # WakaTime OAuth (WP-109)
    WAKATIME_CLIENT_ID,
    WAKATIME_CLIENT_SECRET,
    WAKATIME_REDIRECT_URI,

    # Ory OAuth (WP-187)
    ORY_BASE_URL,
    ORY_CLIENT_ID,
    ORY_CLIENT_SECRET,
    ORY_REDIRECT_URI,

    # L2 Auto-Fix (WP-45)
    GITHUB_BOT_PAT,
    AUTOFIX_REPO,
    AUTOFIX_BRANCH_BASE,
    AUTOFIX_BOT_DIR,
    AUTOFIX_MAX_FILES,
    AUTOFIX_MAX_PROPOSALS,
    AUTOFIX_PROTECTED,

    # Feature flags
    USE_STATE_MACHINE,

    # Логирование
    get_logger,

    # Временная зона
    MOSCOW_TZ,

    # Пути
    BASE_DIR,
    TOPICS_DIR,
    KNOWLEDGE_STRUCTURE_PATH,

    # Режимы и статусы
    Mode,
    MarathonStatus,
    FeedStatus,
    FeedWeekStatus,

    # Настройки пользователя
    DIFFICULTY_LEVELS,
    LEARNING_STYLES,
    EXPERIENCE_LEVELS,
    STUDY_DURATIONS,

    # Content Budget Model (DP.D.027)
    WPM_BASE,
    BLOOM_MULTIPLIER,
    BLOOM_INSTRUCTION,
    calc_words,

    # Сложность (бывш. Bloom)
    COMPLEXITY_LEVELS,
    BLOOM_LEVELS,
    COMPLEXITY_AUTO_UPGRADE_AFTER,
    BLOOM_AUTO_UPGRADE_AFTER,

    # Лимиты
    DAILY_TOPICS_LIMIT,
    MAX_TOPICS_PER_DAY,
    MARATHON_DAYS,

    # Лента
    FEED_DAYS_PER_WEEK,
    FEED_SESSION_DURATION_MIN,
    FEED_SESSION_DURATION_MAX,
    FEED_TOPICS_TO_SUGGEST,

    # Тренировка (WP-55)
    ZP_PRINCIPLES,
    KID_PRINCIPLES,
    KID_MAX_DEPTH,
    TRAINING_MAX_DEPTH,
    TRAINING_COGNITIVE_LEVELS,
    TRAINING_MIN_ANSWER_LENGTH,
    TRAINING_PASS_THRESHOLD,
    TRAINING_PARTIAL_THRESHOLD,
    TRAINING_THRESHOLDS_BY_DEPTH,

    # Интенты
    QUESTION_WORDS,
    TOPIC_REQUEST_PATTERNS,
    COMMAND_WORDS,

    # Категории РП
    WORK_PRODUCT_CATEGORIES,

    # Онтологические правила
    ONTOLOGY_RULES,
    ONTOLOGY_RULES_TOPICS,

    # Markdown sanitizer
    TELEGRAM_MARKDOWN_RULES,

    # Publisher
    PUBLISHER_INTERVAL,

    # WakaTime (WP-60)
    WAKATIME_API_KEY,

    # YooKassa (WP-181)
    YOOKASSA_SHOP_ID,
    YOOKASSA_SECRET_KEY,

    # Channel contexts (SC.118)
    CHANNEL_CONTEXTS,
    get_channel_context,

    # Разработчик (rate limit bypass) + канал наставников марафона
    DEVELOPER_CHAT_ID,
    MENTOR_CHANNEL_ID,

    # Maintenance mode
    MAINTENANCE_MODE,
    MAINTENANCE_REDIRECT_BOT,
    ALLOWED_TESTERS,

    # Event Gateway (WP-268 Phase 2 dual-write)
    EVENT_GATEWAY_URL,
    EVENT_GATEWAY_TIMEOUT,
    EVENT_GATEWAY_ENABLED,

    # WP-253 Пробел C: secrets БД (OAuth-токены)
    SECRETS_URL,
    GITHUB_TOKEN_ENCRYPTION_KEY,

    # WP-253 lift-and-shift (8 мая): остальные BC БД
    PUBLICATION_URL,
    COMMUNITY_URL,
    LEAD_URL,
    REFERENCE_URL,

    # WP-349: URL платформы для /setup
    PLATFORM_URLS,
)

from .onboarding_intents import ONBOARDING_INTENT_MAP  # WP-349 Ф22

__all__ = [
    'BOT_TOKEN',
    'ANTHROPIC_API_KEY',
    'CLAUDE_MODEL_OPUS',
    'CLAUDE_MODEL_SONNET',
    'CLAUDE_MODEL_HAIKU',
    'DATABASE_URL',
    'BOT_DATA_URL',
    'PERSONA_URL',
    'SUBSCRIPTION_URL',
    'INDICATORS_URL',
    'LEARNING_URL',
    'REWARDS_URL',
    'CONSENT_URL',
    'FSM_URL',
    'JOURNAL_URL',
    'HEALTH_URL',
    'KNOWLEDGE_MCP_URL',
    'DIGITAL_TWIN_MCP_URL',
    'GATEWAY_MCP_URL',
    'validate_env',
    'LINEAR_CLIENT_ID',
    'LINEAR_CLIENT_SECRET',
    'LINEAR_REDIRECT_URI',
    'OAUTH_SERVER_PORT',
    'GITHUB_CLIENT_ID',
    'GITHUB_CLIENT_SECRET',
    'GITHUB_REDIRECT_URI',
    'GOOGLE_CALENDAR_CLIENT_ID',
    'GOOGLE_CALENDAR_CLIENT_SECRET',
    'GOOGLE_CALENDAR_REDIRECT_URI',
    'WAKATIME_CLIENT_ID',
    'WAKATIME_CLIENT_SECRET',
    'WAKATIME_REDIRECT_URI',
    'GITHUB_BOT_PAT',
    'AUTOFIX_REPO',
    'AUTOFIX_BRANCH_BASE',
    'AUTOFIX_BOT_DIR',
    'AUTOFIX_MAX_FILES',
    'AUTOFIX_MAX_PROPOSALS',
    'AUTOFIX_PROTECTED',
    'USE_STATE_MACHINE',
    'get_logger',
    'MOSCOW_TZ',
    'BASE_DIR',
    'TOPICS_DIR',
    'KNOWLEDGE_STRUCTURE_PATH',
    'Mode',
    'MarathonStatus',
    'FeedStatus',
    'FeedWeekStatus',
    'DIFFICULTY_LEVELS',
    'LEARNING_STYLES',
    'EXPERIENCE_LEVELS',
    'STUDY_DURATIONS',
    'WPM_BASE',
    'BLOOM_MULTIPLIER',
    'BLOOM_INSTRUCTION',
    'calc_words',
    'COMPLEXITY_LEVELS',
    'BLOOM_LEVELS',
    'COMPLEXITY_AUTO_UPGRADE_AFTER',
    'BLOOM_AUTO_UPGRADE_AFTER',
    'DAILY_TOPICS_LIMIT',
    'MAX_TOPICS_PER_DAY',
    'MARATHON_DAYS',
    'FEED_DAYS_PER_WEEK',
    'FEED_SESSION_DURATION_MIN',
    'FEED_SESSION_DURATION_MAX',
    'FEED_TOPICS_TO_SUGGEST',
    'ZP_PRINCIPLES',
    'KID_PRINCIPLES',
    'KID_MAX_DEPTH',
    'TRAINING_MAX_DEPTH',
    'TRAINING_COGNITIVE_LEVELS',
    'TRAINING_MIN_ANSWER_LENGTH',
    'TRAINING_PASS_THRESHOLD',
    'TRAINING_PARTIAL_THRESHOLD',
    'TRAINING_THRESHOLDS_BY_DEPTH',
    'QUESTION_WORDS',
    'TOPIC_REQUEST_PATTERNS',
    'COMMAND_WORDS',
    'WORK_PRODUCT_CATEGORIES',
    'ONTOLOGY_RULES',
    'ONTOLOGY_RULES_TOPICS',
    'TELEGRAM_MARKDOWN_RULES',
    'PUBLISHER_INTERVAL',
    'WAKATIME_API_KEY',
    'YOOKASSA_SHOP_ID',
    'YOOKASSA_SECRET_KEY',
    'CHANNEL_CONTEXTS',
    'get_channel_context',
    'DEVELOPER_CHAT_ID',
    'MAINTENANCE_MODE',
    'MAINTENANCE_REDIRECT_BOT',
    'ALLOWED_TESTERS',
    'ORY_BASE_URL',
    'ORY_CLIENT_ID',
    'ORY_CLIENT_SECRET',
    'ORY_REDIRECT_URI',
    'EVENT_GATEWAY_URL',
    'EVENT_GATEWAY_TIMEOUT',
    'EVENT_GATEWAY_ENABLED',
    'SECRETS_URL',
    'GITHUB_TOKEN_ENCRYPTION_KEY',
    'PUBLICATION_URL',
    'COMMUNITY_URL',
    'LEAD_URL',
    'REFERENCE_URL',
    'PLATFORM_URLS',
    'ONBOARDING_INTENT_MAP',
]
